
        "planned_shipments": {
            "path": "/planned-shipments",
        },

        "purchases": {
        },

        "shipment_requests": {
            "path": "/shipment-requests",
            "operations": [
                {
                    "method": "GET",
                    "description": "Search all shipment requests. Results are always paginated.",
                    "parameters": [
                        { "name": "guid", "type": "uuid", "required": false },
                        { "name": "fulfilling_vendor_guid", "type": "uuid", "required": false, "references": "vendors.guid" },
                        { "name": "agreement_guid", "type": "uuid", "required": false, "references": "agreements.guid" },
                        { "name": "identifier", "type": "string", "required": false },
                        { "name": "is_open", "type": "boolean", "required": false },
                        { "name": "limit", "type": "integer", "default": 50 },
                        { "name": "offset", "type": "integer", "default": 0 }
                    ],
                    "responses": {
                        "200": { "type": "[shipment_request]" }
                    }
                },
                {
                    "method": "PUT",
                    "path": "/:guid",
                    "description": "Closes an open shipment request ahead of schedule.",
                    "responses": {
                        "201": { "type": "shipment_request" }
                    }
                }
            ]
        },

        "shipment_request_items": {
            "path": "/shipment-request-items",

            "operations": [
                {
                    "method": "GET",
                    "description": "Retrieve the items in a shipment request. Results are always paginated.",
                    "parameters": [
                        { "name": "shipment_request_guid", "type": "string" },
                        { "name": "limit", "type": "integer", "default": 50 },
                        { "name": "offset", "type": "integer", "default": 0 }
                    ],
                    "responses": {
                        "200": { "type": "[shipment_request_item]" }
                    }
                }
            ]
        },

        "receipts": {
            "operations": [
                {
                    "method": "GET",
                    "path": "/:guid",
                    "responses": {
                        "200": { "type": "[receipt]" }
                    }
                },
                {
                    "method": "POST",
                    "parameters": [
                        { "name": "agreement_guid", "type": "string" },
                        { "name": "item_guid", "type": "string" },
                        { "name": "vendor_receipt_number", "type": "string" },
                        { "name": "price", "type": "decimal" }
                    ],
                    "responses": {
                        "200": { "type": "receipt" }
                    }
                },
                {
                    "method": "DELETE",
                    "path": "/:guid"
                }
            ]
        }

    }
}
