
        "planned_shipments": {
            "path": "/planned-shipments",
            "operations": [
                {
                    "method": "GET",
                    "description": "Returns the upcoming planned shipments for a given agreement, filtered by a certain number of days. For example, you can request all planned shipments in the next 30 days - you will then see the actual upcoming dates, if any, that an open shipment request will be cloesd. Results are always paginated.",
                    "parameters": [
                        { "name": "agreement_guid", "type": "string" },
                        { "name": "number_days", "type": "integer", "default": 7 },
                        { "name": "limit", "type": "integer", "default": 50 },
                        { "name": "offset", "type": "integer", "default": 0 }
                    ],
                    "responses": {
                        "200": { "type": "[planned_shipment]" }
                    }
                }
            ]
        },

        "purchases": {
            "operations": [
                {
                    "method": "GET",
                    "description": "Search all purchases. Results are always paginated.",
                    "parameters": [
                        { "name": "guid", "type": "uuid", "required": false },
                        { "name": "vendor_purchase_number", "type": "string", "required": false },
                        { "name": "agreement_guid", "type": "uuid", "required": false, "references": "agreements.guid" },
                        { "name": "item_guid", "type": "uuid", "required": false, "references": "items.guid" },
                        { "name": "limit", "type": "integer", "default": 50 },
                        { "name": "offset", "type": "integer", "default": 0 }
                    ],
                    "responses": {
                        "200": { "type": "[purchase]" }
                    }
                },
                {
                    "method": "GET",
                    "path": "/:guid",
                    "description": "Returns the purchase with this guid.",
                    "responses": {
                        "200": { "type": "purchase" }
                    }
                },
                {
                    "method": "POST",
                    "parameters": [
                        { "name": "vendor_purchase_number", "type": "string" },
                        { "name": "agreement_guid", "type": "string" },
                        { "name": "item_guid", "type": "string" },
                        { "name": "address_name", "type": "string", "required": false },
                        { "name": "address_line1", "type": "string" },
                        { "name": "address_line2", "type": "string", "required": false },
                        { "name": "address_line3", "type": "string", "required": false },
                        { "name": "address_city", "type": "string", "required": false },
                        { "name": "address_state", "type": "string", "required": false },
                        { "name": "address_postal_code", "type": "string" },
                        { "name": "address_country", "type": "string", "description": "3 character iso3166_code for the country. Must be in upper case." },
                        { "name": "address_phone", "type": "string", "required": false },
                        { "name": "price", "type": "decimal", "description": "Price of the item being purchased. Currency is that of the agreement." },
                        { "name": "currency", "type": "string", "description": "3-character upper case iso4217 code for this currency. Validated against the currency in the agreement.", "example": "USD or EUR" }
                    ],
                    "responses": {
                        "201": { "type": "purchase" }
                    }
                }
            ]
        },

        "shipment_requests": {
            "path": "/shipment-requests",
            "operations": [
                {
                    "method": "GET",
                    "description": "Search all shipment requests. Results are always paginated.",
                    "parameters": [
                        { "name": "guid", "type": "uuid", "required": false },
                        { "name": "fulfilling_vendor_guid", "type": "uuid", "required": false, "references": "vendors.guid" },
                        { "name": "agreement_guid", "type": "uuid", "required": false, "references": "agreements.guid" },
                        { "name": "identifier", "type": "string", "required": false },
                        { "name": "is_open", "type": "boolean", "required": false },
                        { "name": "limit", "type": "integer", "default": 50 },
                        { "name": "offset", "type": "integer", "default": 0 }
                    ],
                    "responses": {
                        "200": { "type": "[shipment_request]" }
                    }
                },
                {
                    "method": "PUT",
                    "path": "/:guid",
                    "description": "Closes an open shipment request ahead of schedule.",
                    "responses": {
                        "201": { "type": "shipment_request" }
                    }
                }
            ]
        },

        "shipment_request_items": {
            "path": "/shipment-request-items",

            "operations": [
                {
                    "method": "GET",
                    "description": "Retrieve the items in a shipment request. Results are always paginated.",
                    "parameters": [
                        { "name": "shipment_request_guid", "type": "string" },
                        { "name": "limit", "type": "integer", "default": 50 },
                        { "name": "offset", "type": "integer", "default": 0 }
                    ],
                    "responses": {
                        "200": { "type": "[shipment_request_item]" }
                    }
                }
            ]
        },

        "receipts": {
            "operations": [
                {
                    "method": "GET",
                    "path": "/:guid",
                    "responses": {
                        "200": { "type": "[receipt]" }
                    }
                },
                {
                    "method": "POST",
                    "parameters": [
                        { "name": "agreement_guid", "type": "string" },
                        { "name": "item_guid", "type": "string" },
                        { "name": "vendor_receipt_number", "type": "string" },
                        { "name": "price", "type": "decimal" }
                    ],
                    "responses": {
                        "200": { "type": "receipt" }
                    }
                },
                {
                    "method": "DELETE",
                    "path": "/:guid"
                }
            ]
        }

    }
}
