{{- $fullName := include "deploy.fullname" . -}}
{{- if .Values.ingress.enabled -}}
{{- range $gateway := .Values.ingress.gateways }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $gateway.key }}
  labels:
    app.kubernetes.io/name: {{ include "deploy.name" $ }}
    helm.sh/chart: {{ include "deploy.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ include "deploy.name" $ }}
  annotations:
    kubernetes.io/ingress.class: "ingressgateway"
    kubernetes.io/ingress.tld: {{ $gateway.tld | quote }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP2
      hosts:
      {{- range $host := $gateway.hosts }}
        - {{ $host | quote }}
      {{- end }}
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTP2
      hosts:
      {{- range $host := $gateway.hosts }}
        - {{ $host | quote }}
      {{- end }}
---
{{- end }}
{{- end -}}
