package models

import lib.Constants
import org.joda.time.{DateTime, DateTimeZone}
import org.joda.time.format.DateTimeFormat

case class ApidocHeaders(userAgent: Option[String]) {

  def toJavaString(): String = {
    "/**\n" +
    elements.map(s => s" * $s").mkString("\n") + "\n" +
    " */"
  }

  def toRubyString(): String = elements.map(s => s"# $s").mkString("\n")

  private val elements = Seq(
    Some(s"Generated by apidoc - ${Constants.ApidocUrl}"),
    Some("Generated at " + timestamp()),
    userAgent
  ).flatten

  private val TimeZoneId = "US/Eastern"

  private def timestamp(): String = {
    DateTimeFormat.longDateTime.withZone(DateTimeZone.forID(TimeZoneId)).print(new DateTime())
  }

}
