{{- $fullName := include "deploy.fullname" . -}}
{{- range $stage, $deployment := index .Values "deployments" }}
{{- if and $deployment.autoscaleEnabled $deployment.minReplicas }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}-{{ $stage }}
  labels:
    helm.sh/chart: {{ include "deploy.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "deploy.name" $ }}
    app.kubernetes.io/stage: {{ $stage }}
    app: {{ include "deploy.name" $ }}
spec:
  minReplicas: {{ $deployment.minReplicas }}
  maxReplicas: {{ $deployment.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}-{{ $stage }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetCPUUtilizationPercentage: {{ $deployment.targetCPUUtilizationPercentage }}
---
{{- end -}}
{{- end -}}
