#!/usr/bin/env ruby

# ./upload
# ./upload 0.8.18
# ./upload 0.8.18 localhost http://localhost:9000

CLI_PATH = "/web/apidoc-cli/bin/apidoc"
PRODUCTION_HOST = "http://www.apidoc.me"

version = ARGV.shift.to_s.strip
profile = ARGV.shift.to_s.strip
host = ARGV.shift.to_s.strip

number_defaults = 0
if version == ""
  version = `git describe`.strip
  number_defaults += 1
end

if profile == ""
  profile = "localhost"
  number_defaults += 1
end

if host == ""
  host = (profile == "localhost") ? "http://localhost:9000" : PRODUCTION_HOST
  number_defaults += 1
end

puts ""
puts " Profile: #{profile}"
puts "    Host: #{host}"
puts " Version: #{version}"
puts ""

if number_defaults > 0
  answer = nil
  while answer.nil?
    print "Continue? (y/n): "
    response = $stdin.gets.strip.downcase
    if response.match(/^y/)
      answer = true
    elsif response.match(/^n/)
      puts "exiting"
      exit(0)
    end
  end
end

def print_error(msg)
  puts ""
  puts msg
  puts ""
end

def cli(command, opts={})
  profile = opts.delete(:profile)
  if !opts.empty?
    raise "Invalid keys: #{opts.keys.inspect}"
  end

  env = {}
  env["PROFILE"] = profile.to_s.strip if profile.to_s.strip != "default"
  builder = env.select { |k, v| v != "" }.map { |k,v| "export #{k}=#{v}" }

  builder << "#{CLI_PATH} #{command}"
  cmd = builder.join(" && ")
  puts cmd
  puts `#{cmd}`.strip
end

def upload(profile, host, version, application, path)
  dir = File.dirname(__FILE__)
  cli("upload bryzek #{application} #{File.join(dir, path)} --version #{version}", :profile => profile)
end

upload(profile, host, version, "apidoc-spec", "../spec/spec.json")
upload(profile, host, version, "apidoc-common", "../spec/common.json")
upload(profile, host, version, "apidoc-generator", "../spec/generator.json")
upload(profile, host, version, "apidoc-internal", "../spec/internal.json")
upload(profile, host, version, "apidoc-api", "../spec/api.json")



