#!/bin/sh

curl \
     -X PUT \
     -H "X-Auth: 12345" \
     -H "Content-Type: application/json" \
     -d @./api.json \
     http://localhost:9001/gilt/apidoc/0.0.4

curl \
     -X PUT \
     -H "X-Auth: 12345" \
     -H "Content-Type: application/json" \
     -d @./api.json \
     http://localhost:9001/gilt/apidoc/0.0.5

curl \
     -H "X-Auth: 12345" \
     http://localhost:9001/gilt/apidoc/0.0.5

curl -H "X-Auth: 12345" 'http://localhost:9001/users?email=otto@gilt.com'
curl -H "X-Auth: 12345" 'http://localhost:9001/users?email=mbryzek@yahoo.com'

curl -H "X-Auth: 12345" 'http://localhost:9001/organizations?name=gilt'
curl -H "X-Auth: 12345" 'http://localhost:9001/gilt'

curl -XPOST -H "X-Auth: 12345" -H "Content-Type: application/json" -d@./example/user.json 'http://localhost:9001/users'
